#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") WORKINGDIR

'$(basename "$0")' tidies up the HTML files in the directory tree 'WORKINGDIR'
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#


function tidyfile
{
    echo ============================================================
    echo $(pwd)
    if stat -t $* > /dev/null 2>&1; then
        tidy -mq --gnu-emacs yes --indent auto --indent-spaces 2 --wrap 0 $*
        echo "exit value: $?"
        sed -i '/^\s*$/d' $*
    fi
}

if [ ! -d "$1" ]; then
    exitWith 1 "Error : the directory '$1' doesn't exist."
fi

#cd "$1"
#exitOnError 1 "Could not 'cd' into '$1'"

walkdir "$1" tidyfile \*.html
