#!/bin/bash

sourceDir=source
pagesFile=tagged-pages.txt
tagsFile=tags.txt
tagsDir=$sourceDir/tags
tsvSingleTag=data.tsv
tsvAllTags=source/tags/data.tsv

# Create a file listing all pages having tags, one page per line. Example:
# path_to_page: tag1<tab>tag2
grep -r --include=header.inc \:tags\: | grep -v "\.\.\ \+\:tags\:" | cut -d: -f 1,4 | sed 's/header.inc/index/g' | tr '|' $'\t' > $pagesFile

# Create a file listing all tags, one tagname per line. Example:
# tagname<tab>path_to_page1<tab>path_to_page2
while read tagname; do
    echo -ne $tagname'\t'
    grep -w "$tagname" $pagesFile | cut -d: -f1 | tr $'\n' $'\t' | head -c -1
    echo
done < <(cut -d: -f2 $pagesFile | cut -f1- --output-delimiter=$'\n' | sed 's/^ *//g' | sort -u) > $tagsFile

# Create a .tsv file with data for the tags table
while read tagname; do
    tagname_fs="$(echo $tagname | tr ' ' '_')"
    echo -e ':doc:`'/tags/$tagname_fs/index'`\t:numpages:`'$(grep -wc "$tagname" "$pagesFile")'`'
done < <(cut -f1 $tagsFile) > $tsvAllTags

# Read $tagsFile and create source/tags/tag1/index.rst, source/tags/tag2/index.rst etc ...
#

# Delete all tags subdirectories
find $tagsDir -mindepth 1 -type d | xargs rm -rf

# Create subdir for every tagname and create an index.rst file in it
while read tagname; do
    tagname_fs="$(echo $tagname | tr ' ' '_')"
    tagdir="$tagsDir/$tagname_fs"
    mkdir -p "$tagdir"
    echo "$tagname" > "$tagdir/index.rst"
    echo "$tagname" | tr [:print:] '=' >> "$tagdir/index.rst"
    echo >> "$tagdir/index.rst"
    echo ".. role:: timestamp" >> "$tagdir/index.rst"
    echo ".. role:: greytext" >> "$tagdir/index.rst"
    echo >> "$tagdir/index.rst"
    echo "List of pages having the tag \'$tagname\':" >> "$tagdir/index.rst"
    echo >> "$tagdir/index.rst"
    echo  .. csv-table:: >> "$tagdir/index.rst"
    echo " :widths: 70,70,40"  >> "$tagdir/index.rst"
    echo " :class: pagetable"  >> "$tagdir/index.rst"
#    echo " :header: \"Name\", \"Last modified\", \"Other tags\"" >> "$tagdir/index.rst"
#    echo " :stub-columns: 1" >> "$tagdir/index.rst"
    echo " :delim: tab" >> "$tagdir/index.rst"
    echo " :file: $tsvSingleTag" >> "$tagdir/index.rst"
    echo >> "$tagdir/index.rst"

    # Iterate over all pages having tag '$tagname' and add a row for every page in tsvdata.txt
    tsvFile="$tagdir/$tsvSingleTag"

    echo -n > "$tsvFile"
    while read page; do
        echo -ne :doc:\`$(echo $page | sed "s/^$sourceDir//g")\`'\t:timestamp:`'$(date -r $page.rst "+%Y-%m-%d %H:%M:%S")'`\t' >> $tsvFile
        firstTag=true
        while read othertagname; do
            if [ "$tagname" != "$othertagname" ]; then
                othertagname_fs="$(echo $othertagname | tr ' ' '_')"
                if ! "$firstTag"; then
                    echo -n ':greytext:`|` ' >> "$tsvFile"
                fi
                firstTag=false
                echo -n ":doc:\`/tags/$othertagname_fs/index\` " >> "$tsvFile"
            fi
        done < <(grep $page $pagesFile | cut -d: -f2- | cut -f1- --output-delimiter=$'\n' | sed 's/^ *//g' | sort -u)
        echo >> "$tsvFile"
    # TODO: pass $tagname through some grep escape filter
    done < <(grep -w "^$tagname" "$tagsFile" | cut -f2- --output-delimiter=$'\n')

    # Sort the TSV data by date, newest first
    sort -r -t $'\t' -k 2 "$tsvFile" -o "$tsvFile"

    # Create header.inc
    echo ":notimestamp:" > "$tagdir/header.inc"
done < <(cut -f1 "$tagsFile")
